[package]
name = "Neonix!"
description = "Neonix! game"
author = "KiwiStation"
version = "0.0.1"
icon = "game/icon.png"

[build]
default = ["love", "win64", "linux"]

[directories]
source = "game"
build = "build"